/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "rtthread.h"
#include <time.h>
#include "stdio.h"
#include <string.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x07)
#define ID_SPINBOX_0    (GUI_ID_USER + 0x08)
#define ID_SPINBOX_1    (GUI_ID_USER + 0x0A)
#define ID_SPINBOX_2    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_0    (GUI_ID_USER + 0x0C)
#define ID_SPINBOX_3    (GUI_ID_USER + 0x0D)
#define ID_SPINBOX_4    (GUI_ID_USER + 0x0E)
#define ID_SPINBOX_5    (GUI_ID_USER + 0x0F)
#define ID_TEXT_0    (GUI_ID_USER + 0x10)
#define ID_TEXT_1    (GUI_ID_USER + 0x11)
#define ID_TEXT_2    (GUI_ID_USER + 0x12)
#define ID_TEXT_3    (GUI_ID_USER + 0x13)
#define ID_TEXT_4    (GUI_ID_USER + 0x14)
#define ID_TEXT_5    (GUI_ID_USER + 0x15)
#define ID_TEXT_6    (GUI_ID_USER + 0x16)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Clock", ID_FRAMEWIN_0, 60, 60, 320, 240, FRAMEWIN_CF_MOVEABLE, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 10, 95, 90, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_1, 110, 95, 90, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_2, 210, 95, 90, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SAVE", ID_BUTTON_0, 108, 162, 82, 34, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_3, 10, 40, 90, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_4, 110, 40, 90, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_5, 210, 40, 90, 35, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TIME DATE", ID_TEXT_0, 59, 11, 250, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Year", ID_TEXT_1, 25, 75, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Month", ID_TEXT_2, 125, 75, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Date", ID_TEXT_3, 225, 75, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hour", ID_TEXT_4, 25, 130, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Min", ID_TEXT_5, 125, 130, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sec", ID_TEXT_6, 225, 130, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*
*********************************************************************************************************
*	函 数 名: InitDialog
*	功能说明: 对话框回调函数初始化消息的执行函数
*	形    参: pMsg  消息
*	返 回 值: 无
*********************************************************************************************************
*/
static void InitDialog(WM_MESSAGE * pMsg)
{
	  WM_HWIN hItem;
	  WM_HWIN hWin = pMsg->hWin;
	
		char temp_txt[100];
	  time_t now;
	  struct tm *p_tm;
    struct tm tm_new;
	
	  now = time(RT_NULL);
	  p_tm = localtime(&now);
    sprintf(temp_txt,"%s\n", ctime(&now));
		memcpy(&tm_new, p_tm, sizeof(struct tm)); 	
	  tm_new.tm_year=(tm_new.tm_year-116)+2016;
	  tm_new.tm_mon=(tm_new.tm_mon-6)+7;
	  tm_new.tm_yday=(tm_new.tm_yday-191)+9;
	
	  

  	GUI_SetBkColor(GUI_WHITE);  

	  //
    //FRAMEWIN
    //
    FRAMEWIN_SetFont(hWin,&GUI_Font24B_ASCII);
    FRAMEWIN_SetTextAlign(hWin,GUI_TA_VCENTER|GUI_TA_CENTER);
    FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);
    FRAMEWIN_AddMaxButton(hWin, FRAMEWIN_BUTTON_RIGHT, 1);
    FRAMEWIN_AddMinButton(hWin, FRAMEWIN_BUTTON_RIGHT, 2);
    FRAMEWIN_SetTitleHeight(hWin,25);
	
	
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
		SPINBOX_SetRange(hItem,0,23);
		SPINBOX_SetValue(hItem,tm_new.tm_hour);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
		SPINBOX_SetRange(hItem,0,60);
		SPINBOX_SetValue(hItem,tm_new.tm_min);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
    SPINBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
		SPINBOX_SetRange(hItem,0,60);
		SPINBOX_SetValue(hItem,tm_new.tm_sec);
    //
    // Initialization of 'SAVE'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_3);
    SPINBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
		SPINBOX_SetRange(hItem,2000,4016);
		SPINBOX_SetValue(hItem,tm_new.tm_year);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_4);
    SPINBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
		SPINBOX_SetRange(hItem,1,12);
		SPINBOX_SetValue(hItem,tm_new.tm_mon);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_5);
    SPINBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
		SPINBOX_SetRange(hItem,1,31);
		SPINBOX_SetValue(hItem,tm_new.tm_mday);
    //
    // Initialization of 'TIME DATE'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
		TEXT_SetText(hItem,temp_txt);
    //
    // Initialization of 'Year'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Month'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Date'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Hour'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Min'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Sec'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
		
		//WM_SetCallback(WM_GetClientWindow(hWin), _cbBkTime);
   // WM_CreateTimer(WM_HBKWIN, 0, 1000, 0);

}

static void _cbSavedate(WM_MESSAGE * pMsg)
{
	unsigned int temp_year,temp_mon,temp_day,temp_hour,temp_min,temp_sec;
  WM_HWIN hItem;
	WM_HWIN hWin = pMsg->hWin;
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
	temp_hour=SPINBOX_GetValue(hItem);
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
	temp_min=SPINBOX_GetValue(hItem);
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
	temp_sec=SPINBOX_GetValue(hItem);
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_3);
	temp_year=SPINBOX_GetValue(hItem);
		
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_4);
	temp_mon=SPINBOX_GetValue(hItem);
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_5);
	temp_day=SPINBOX_GetValue(hItem);
	
	set_date(temp_year,temp_mon,temp_day);
	
	set_time(temp_hour,temp_min,temp_sec);
		
}

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		InitDialog(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_2: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'SAVE'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			_cbSavedate(pMsg);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_3: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_4: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_5: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewinclock(void);
WM_HWIN CreateFramewinclock(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, 0, 0, 0);
  return hWin;
}

void Clock_set(WM_HWIN hWin)
{
  CreateFramewinclock();
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
